language: ruby

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8

bundler_args: "--without documentation --path bundle"

install:
  - gem install bundler -v '2.0.1'
  - bundle install

after_install:
  - rake install

script:
  - bundle exec rake spec

sudo: required