language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.1.3

bundler_args: "--without documentation --path bundle"

install:
  - gem install bundler

script:
  - bundle exec rake spec

sudo: required